apiVersion: apps/v1
kind: Deployment
metadata:
  name:  db-test
  namespace: default
  labels:
    app: db-test
spec:
  replicas: 16
  selector:
    matchLabels:
      app: db-test
  template:
    metadata:
      labels:
        app: db-test
    spec:
      containers:
        - name: db-test
          image: sytgj7896321/dbtool:1.1.0
          args:
            - 'mysql'
            - '--host'
            - 'temp.cr5sg9unpmla.us-west-2.rds.amazonaws.com'
            - '--username'
            - 'admin'
            - '--password'
            - 'Admin#1234'
            - '--instance'
            - 'sys'
            - '--sql'
            - 'select * from metrics limit 1;'
          resources:
            limits:
              cpu: 2000m
              memory: 512M
            requests:
              cpu: 200m
              memory: 64M
